### ISSUE TITLE
パターンA：縦スクロール版デザイン

### ISSUE THREAD

**Issue by meihaku** [team-test/team#2]
ヘッダーにロゴとメニュー、WORKSの画像を縦に並べる。フッターを用意して会社情報などを載せたデザイン。

**Comment by meihaku** [comment]
てすと

**Comment by meihaku** [comment]
第一版のデザインが出来ました。ご確認お願いします。@b-san2
![top](https://user-images.githubusercontent.com/34340121/33796318-4f94421a-dd35-11e7-9156-c5131f353e95.png)

**Comment by b-san2** [comment]
ｂさん　テスト

**Comment by meihaku** [comment]
@b-san2

**Comment by b-san2** [comment]
@meihaku 
this is test.

**Comment by b-san2** [comment]
@meihaku 
one more test

**Comment by meihaku** [comment]
確認お願い致します。@b-san2
